version = 3
final_space = true

[palette] # TokyoNight color palette
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

yellow2 = "#ff9e64"
cyan2 = "#73daca"
cyan3 = "#b4f9f8"
blue2 = "#2ac3de"
magenta2 = "#dca0c1"
#14141b
# [palette] # Ayu-dark color palette
# black = "#1e232b"
# red = "#ea6c73"
# green = "#7fd962"
# yellow = "#f9af4f"
# blue = "#53bdfa"
# magenta = "#cda1fa"
# cyan = "#90e1c6"
# white = "#c7c7c7"

# black2 = "#686868"
# red2 = "#f07178"
# green2 = "#aad94c"
# yellow2 = "#ffb454"
# blue2 = "#59c2ff"
# magenta2 = "#d2a6ff"
# cyan2 = "#95e6cb"
# white2 = "#ffffff"

# [palette] # Sonokai color palette
# red = "#fb617e"
# green = "#9ed06c"
# yellow = "#edc763"
# blue = "#6dcae8"
# magenta = "#bb97ee"
# cyan = "#77d5f0"

# [palette] # Catppuccin Mocha color pallete
# black = "#45475a"
# red = "#f38ba8"
# green = "#a6e3a1"
# yellow = "#f9e2af"
# blue = "#89b4fa"
# magenta = "#f5c2e7"
# cyan = "#94e2d5"
# white = "#a6adc8"

# black2 = "#585b70"
# red2 = "#f37799"
# green2 = "#89d88b"
# yellow2 = "#ebd391"
# blue2 = "#74a8fc"
# magenta2 = "#f2aede"
# cyan2 = "#6bd7ca"
# white2 = "#bac2de"

[[blocks]]
  type = "prompt"
  alignment = "left"

  # [[blocks.segments]]
  #   type = "text"
  #   style = "plain"
  #   foreground = "#ffffff"
  #   template = "<#eaeaea>\u23a7</> "

  [[blocks.segments]]
    template = "{{ if eq .Code 0 }}{{ else }}\uf444 \uf467 {{ .Code }} \uf444{{ end }}"
    foreground = "p:red"
    background = "transparent"
    type = "status"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
    template = "\uf444 \uf007 {{ .UserName }}<p:blue>@</><p:blue>{{ .HostName }}</> \uf444"
    foreground = "p:blue"
    background = "transparent"
    type = "session"
    style = "plain"
    foreground_templates = ["{{ if .Root }}p:red{{ end }}"]

    [blocks.segments.properties]
      cache_duration = "none"

  [[blocks.segments]]
    template = "\uf444 {{ if .Writable }}\uf07b{{ else }}<p:magenta2>\uf456</>{{ end }} {{ .Path }} \uf444"
    foreground = "p:magenta2"
    background = "transparent"
    type = "path"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
      folder_icon = "\uf07b"
      style = "full"

  [[blocks.segments]]
    template = "\uf444 {{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}   {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} \uf444"
    foreground = "p:magenta"
    background = "transparent"
    type = "git"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      branch_icon = "\ue725 "
      
  [[blocks.segments]]
    template = "\uf444 \uf253 {{ .FormattedMs }} \uf444"
    foreground = "p:cyan"
    background = "transparent"
    type = "executiontime"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
      always_enabled = true

# [[blocks]]
#   type = "prompt"
#   alignment = "right"
#   [[blocks.segments]]
#     type = "text"
#     style = "plain"
#     foreground = "#ffffff"
#     template = "<#eaeaea>\u23ab</>"

# [[blocks]]
#   type = "rprompt"
#   alignment = "right"
#   [[blocks.segments]]
#     type = "text"
#     style = "plain"
#     foreground = "#ffffff"
#     template = "<#eaeaea>\u23ad</>"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true
  [[blocks.segments]]
#    template = "\u2570"
    template = "\u2009\u2937 "
    foreground = "p:green"
    background = "transparent"
    type = "text"
    style = "plain"

    [blocks.segments.properties]
      cache_duration = "none"
